CREATE TABLE ALUNOS (
	MATRICULA VARCHAR(10) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    TURMA VARCHAR(40) NOT NULL,
    FONE VARCHAR(15) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    PRIMARY KEY (MATRICULA)
);