POST http://localhost:3000/alunos/novoAluno
Content-Type: application/json

{ 
    "matricula": "4428999",
    "nome":  "Joel",
    "email": "joelma@email.com",
    "data_nascimento": "2000-02-20",
    "turma": "7° Ano A",
    "fone": "(84) 997979799",
    "sexo": "F"
}

###

GET http://localhost:3000/alunos/listarAlunos

###
GET http://localhost:3000/alunos/buscarAluno/4423

###
GET http://localhost:3000/alunos/buscarAlunoTurma/7° Ano B

###
DELETE  http://localhost:3000/alunos/deletarAluno/4423
